name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25
          cache: gradle

      - name: Build and verify
        if: github.event_name == 'pull_request'
        run: ./gradlew build --stacktrace

      - name: Publish to repo
        if: github.event_name != 'pull_request'
        run: ./gradlew publish --no-daemon --stacktrace --no-configuration-cache
        env:
          PRIVATE_MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          PRIVATE_MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}